#!/usr/bin/env python
"""
Hiero Review Tool Installer
===========================
Installation script for deploying the tool to Hiero's plugin directory.
"""
import os
import sys
import shutil
import argparse
from pathlib import Path


def get_hiero_plugin_dir() -> Path:
    """Get the Hiero plugin directory based on OS."""
    if sys.platform == "win32":
        base = Path(os.environ.get("USERPROFILE", "~"))
    else:
        base = Path.home()
    
    return base / ".nuke" / "Python"


def get_source_dir() -> Path:
    """Get the source directory (parent of install/)."""
    return Path(__file__).parent.parent


def install(target_dir: Path = None, force: bool = False) -> bool:
    """
    Install the Hiero Review Tool.
    
    Args:
        target_dir: Target installation directory
        force: Overwrite existing installation
        
    Returns:
        True if successful
    """
    source_dir = get_source_dir()
    
    if target_dir is None:
        target_dir = get_hiero_plugin_dir() / "hiero_review"
    
    print(f"Installing Hiero Review Tool...")
    print(f"  Source: {source_dir}")
    print(f"  Target: {target_dir}")
    
    # Check if already installed
    if target_dir.exists():
        if force:
            print(f"  Removing existing installation...")
            shutil.rmtree(target_dir)
        else:
            print(f"  ERROR: Target directory already exists. Use --force to overwrite.")
            return False
    
    # Create target directory
    target_dir.mkdir(parents=True, exist_ok=True)
    
    # Copy source files
    src_dir = source_dir / "src"
    if src_dir.exists():
        print(f"  Copying source files...")
        shutil.copytree(src_dir, target_dir / "src")
    
    # Copy config
    config_dir = source_dir / "config"
    if config_dir.exists():
        print(f"  Copying configuration...")
        shutil.copytree(config_dir, target_dir / "config")
    
    # Copy launcher
    launcher = source_dir / "hiero_launcher.py"
    if launcher.exists():
        print(f"  Copying launcher...")
        shutil.copy(launcher, target_dir / "hiero_launcher.py")
    
    # Create startup script
    startup_script = target_dir / "startup.py"
    startup_script.write_text('''"""
Hiero Review Tool Startup Script
Auto-generated by installer.
"""
import sys
from pathlib import Path

# Add tool to path
tool_dir = Path(__file__).parent
if str(tool_dir) not in sys.path:
    sys.path.insert(0, str(tool_dir))

# Register menu
try:
    from src.ui import register_menu
    register_menu()
    print("Hiero Review Tool loaded successfully.")
except ImportError as e:
    print(f"Warning: Could not load Hiero Review Tool: {e}")
''')
    
    print(f"  Installation complete!")
    print(f"\n  To use the tool:")
    print(f"    1. Restart Hiero")
    print(f"    2. Go to Tools > Review Tool")
    
    return True


def uninstall(target_dir: Path = None) -> bool:
    """
    Uninstall the Hiero Review Tool.
    
    Args:
        target_dir: Installation directory to remove
        
    Returns:
        True if successful
    """
    if target_dir is None:
        target_dir = get_hiero_plugin_dir() / "hiero_review"
    
    if not target_dir.exists():
        print(f"  Tool not installed at {target_dir}")
        return False
    
    print(f"Uninstalling Hiero Review Tool from {target_dir}...")
    shutil.rmtree(target_dir)
    print(f"  Uninstallation complete!")
    
    return True


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Hiero Review Tool Installer")
    parser.add_argument("action", choices=["install", "uninstall"], help="Action to perform")
    parser.add_argument("--target", type=Path, help="Target directory")
    parser.add_argument("--force", action="store_true", help="Force overwrite")
    
    args = parser.parse_args()
    
    if args.action == "install":
        success = install(args.target, args.force)
    else:
        success = uninstall(args.target)
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()

